"""Tabela escalacao e tabela jogador-escalacao

Revision ID: 355ee34f9ab3
Revises: 134ff804bc84
Create Date: 2024-08-28 14:59:41.657706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '355ee34f9ab3'
down_revision: Union[str, None] = '134ff804bc84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escalacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['time_id'], ['time.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escalacao_jogador',
    sa.Column('escalacao_id', sa.Integer(), nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=False),
    sa.Column('treinador', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['escalacao_id'], ['escalacao.id'], ),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogador.id'], ),
    sa.PrimaryKeyConstraint('escalacao_id', 'jogador_id')
    )
    with op.batch_alter_table('jogador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_jogador_time', type_='foreignkey')
        batch_op.create_foreign_key("fk_jogador_foto", 'arquivos', ['foto_id'], ['id'])
        batch_op.drop_column('time_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint("fk_jogador_foto", type_='foreignkey')
        batch_op.create_foreign_key('fk_jogador_time', 'time', ['time_id'], ['id'])
        batch_op.drop_column('foto_id')

    op.drop_table('escalacao_jogador')
    op.drop_table('escalacao')
    # ### end Alembic commands ###
