"""SQLite

Revision ID: 5502403bc5f6
Revises: 
Create Date: 2024-09-05 10:59:23.887846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5502403bc5f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=False),
    sa.Column('presencial', sa.Boolean(), nullable=False),
    sa.Column('premiacao', sa.Numeric(scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('foto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('nome_foto', sa.String(), nullable=False),
    sa.Column('dados', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mapa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('noticia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cabecalho', sa.String(length=100), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('autor', sa.String(length=100), nullable=False),
    sa.Column('regiao', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ranking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('regiao', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('regiao')
    )
    op.create_table('time',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('escalacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['time_id'], ['time.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jogador',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('apelido', sa.String(length=100), nullable=False),
    sa.Column('nacionalidade', sa.String(length=255), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('genero', sa.String(length=50), nullable=False),
    sa.Column('foto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foto_id'], ['foto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partida',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_evento',
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['time.id'], ),
    sa.PrimaryKeyConstraint('evento_id', 'time_id')
    )
    op.create_table('time_ranking',
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('ranking_id', sa.Integer(), nullable=False),
    sa.Column('posicao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ranking_id'], ['ranking.id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['time.id'], ),
    sa.PrimaryKeyConstraint('time_id', 'ranking_id'),
    sa.UniqueConstraint('time_id', 'ranking_id', 'posicao', name='time_posicao_ranking')
    )
    op.create_table('trofeu',
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('foto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['foto_id'], ['foto.id'], ),
    sa.PrimaryKeyConstraint('evento_id')
    )
    op.create_table('escalacao_jogador',
    sa.Column('escalacao_id', sa.Integer(), nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=False),
    sa.Column('treinador', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['escalacao_id'], ['escalacao.id'], ),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogador.id'], ),
    sa.PrimaryKeyConstraint('escalacao_id', 'jogador_id')
    )
    op.create_table('jogador_trofeu',
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['trofeu.evento_id'], ),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogador.id'], ),
    sa.PrimaryKeyConstraint('evento_id', 'jogador_id')
    )
    op.create_table('mapa_partida',
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('mapa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mapa_id'], ['mapa.id'], ),
    sa.ForeignKeyConstraint(['partida_id'], ['partida.id'], ),
    sa.PrimaryKeyConstraint('partida_id', 'mapa_id')
    )
    op.create_table('time_partida',
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partida_id'], ['partida.id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['time.id'], ),
    sa.PrimaryKeyConstraint('partida_id', 'time_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_partida')
    op.drop_table('mapa_partida')
    op.drop_table('jogador_trofeu')
    op.drop_table('escalacao_jogador')
    op.drop_table('trofeu')
    op.drop_table('time_ranking')
    op.drop_table('time_evento')
    op.drop_table('partida')
    op.drop_table('jogador')
    op.drop_table('escalacao')
    op.drop_table('time')
    op.drop_table('ranking')
    op.drop_table('noticia')
    op.drop_table('mapa')
    op.drop_table('foto')
    op.drop_table('evento')
    # ### end Alembic commands ###
