"""Tabela time x ranking

Revision ID: 963b1d141265
Revises: 4ebbfb9e7bf6
Create Date: 2024-09-03 18:30:59.693189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '963b1d141265'
down_revision: Union[str, None] = '4ebbfb9e7bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_ranking',
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('ranking_id', sa.Integer(), nullable=False),
    sa.Column('posicao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ranking_id'], ['ranking.id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['time.id'], ),
    sa.PrimaryKeyConstraint('time_id', 'ranking_id'),
    sa.UniqueConstraint('time_id', 'ranking_id', 'posicao', name='time_posicao_ranking')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_ranking')
    # ### end Alembic commands ###
