"""Tabela mapa x partida

Revision ID: b15e5c59b3c5
Revises: 1ead2d392937
Create Date: 2024-09-03 17:45:03.634849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b15e5c59b3c5'
down_revision: Union[str, None] = '1ead2d392937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapa_partida',
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('mapa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mapa_id'], ['mapa.id'], ),
    sa.ForeignKeyConstraint(['partida_id'], ['partida.id'], ),
    sa.PrimaryKeyConstraint('partida_id', 'mapa_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mapa_partida')
    # ### end Alembic commands ###
