"""altera tabela arquivo

Revision ID: b81171e060be
Revises: 355ee34f9ab3
Create Date: 2024-08-28 15:33:52.827447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b81171e060be'
down_revision: Union[str, None] = '355ee34f9ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('nome_foto', sa.String(), nullable=False),
    sa.Column('dados', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('foto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_foto_id'), ['id'], unique=False)

    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.drop_index('ix_arquivos_id')

    with op.batch_alter_table('jogador', schema=None) as batch_op:
        batch_op.drop_constraint('fk_jogador_foto', type_='foreignkey')
        batch_op.create_foreign_key("fk_jogador_foto", 'foto', ['foto_id'], ['id'])

    op.drop_table('arquivos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogador', schema=None) as batch_op:
        batch_op.drop_constraint("fk_jogador_foto", type_='foreignkey')
        batch_op.create_foreign_key('fk_jogador_foto', 'arquivos', ['foto_id'], ['id'])

    op.create_table('arquivos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), nullable=False),
    sa.Column('nome_arquivo', sa.VARCHAR(), nullable=False),
    sa.Column('dados', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.create_index('ix_arquivos_id', ['id'], unique=False)

    with op.batch_alter_table('foto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_foto_id'))

    op.drop_table('foto')
    # ### end Alembic commands ###
