"""Tabela arquivos

Revision ID: 134ff804bc84
Revises: cedb8953d000
Create Date: 2024-08-28 09:00:57.949713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134ff804bc84'
down_revision: Union[str, None] = 'cedb8953d000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arquivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('nome_arquivo', sa.String(), nullable=False),
    sa.Column('dados', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arquivos_id'), ['id'], unique=False)

    with op.batch_alter_table('jogador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apelido', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('genero', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogador', schema=None) as batch_op:
        batch_op.drop_column('genero')
        batch_op.drop_column('apelido')

    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arquivos_id'))

    op.drop_table('arquivos')
    # ### end Alembic commands ###
