"""Tabela jogador x trofeu

Revision ID: 2b4050823b31
Revises: 3314222eaea1
Create Date: 2024-09-02 10:28:42.674926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b4050823b31'
down_revision: Union[str, None] = '3314222eaea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jogador_trofeu',
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['trofeu.evento_id'], ),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogador.id'], ),
    sa.PrimaryKeyConstraint('evento_id', 'jogador_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jogador_trofeu')
    # ### end Alembic commands ###
