"""Tabela trofeu

Revision ID: 3314222eaea1
Revises: 5a9cc9f575f3
Create Date: 2024-09-02 09:05:25.660091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3314222eaea1'
down_revision: Union[str, None] = '5a9cc9f575f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trofeu',
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('foto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['foto_id'], ['foto.id'], ),
    sa.PrimaryKeyConstraint('evento_id')
    )
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=100), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('nome')

    op.drop_table('trofeu')
    # ### end Alembic commands ###
