"""Tabela evento

Revision ID: 5a9cc9f575f3
Revises: b81171e060be
Create Date: 2024-09-02 08:32:11.005354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a9cc9f575f3'
down_revision: Union[str, None] = 'b81171e060be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=False),
    sa.Column('presencial', sa.Boolean(), nullable=False),
    sa.Column('premiacao', sa.Numeric(scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evento')
    # ### end Alembic commands ###
