"""Atributos unicos

Revision ID: 81d9c68ac453
Revises: b15e5c59b3c5
Create Date: 2024-09-03 18:11:24.211098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d9c68ac453'
down_revision: Union[str, None] = 'b15e5c59b3c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.create_unique_constraint("evento-nome", ['nome'])

    with op.batch_alter_table('mapa', schema=None) as batch_op:
        batch_op.create_unique_constraint("mapa-nome", ['nome'])

    with op.batch_alter_table('time', schema=None) as batch_op:
        batch_op.create_unique_constraint("time-nome", ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time', schema=None) as batch_op:
        batch_op.drop_constraint("time-nome", type_='unique')

    with op.batch_alter_table('mapa', schema=None) as batch_op:
        batch_op.drop_constraint("mapa-nome", type_='unique')

    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.drop_constraint("evento-nome", type_='unique')

    # ### end Alembic commands ###
