"""Tabela noticia

Revision ID: cfe5c73f7471
Revises: 963b1d141265
Create Date: 2024-09-03 18:51:19.080701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe5c73f7471'
down_revision: Union[str, None] = '963b1d141265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noticia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cabecalho', sa.String(length=100), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('autor', sa.String(length=100), nullable=False),
    sa.Column('regiao', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noticia')
    # ### end Alembic commands ###
